-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMvleR7pkbDBYr+L0
B0opZ31tGy1BEIj8y/eNnJwtkm2gCgYIKoZIzj0DAQehRANCAATzdiLiMt+DP07z
LxwuqM/MRyKhsdbRKGgcdK1M2QEdxSDRZhSIBzZMcMoU5Afr7HSMRLVB+6+jWm3M
tUyeB/Jj
-----END PRIVATE KEY-----