name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Xcode 15 build 4
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

    - name: Install Homebrew if not present
      run: |
        which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"

    - name: Set up Homebrew and Install Tuist
      run: |
        brew update
        brew tap tuist/tuist
        brew install tuist

    - name: Fetch dependencies
      run: tuist install

    - name: Generate project
      run: tuist generate

    - name: Build and Test
      run: tuist test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          DerivedData/**/Logs/Test/*.xcresult
